const  traduzirErrorPostGre = require('./traducoesBanco');

const erro_generico = 'Ocorreu um erro! Tente novamente!';
const erro_falha_conexao = 'Falha na conexão';
const nenhum_dado_encontrado = 'Nenhum dado foi encontrado';
const campo_nulo_nao_permitido = 'Campo nulo não permitido!';
const item_ja_cadastrado = 'Item já cadastrado!';
const erro_ao_excluir = 'Erro ao excluir!';
campo_tamanho_maior_que_permitido = 'Tamanho do campo maior do que o máximo permitido';

const erros = {
    ETIMEDOUT: erro_falha_conexao, // connect ETIMEDOUT
    'No data returned from the query.': nenhum_dado_encontrado, // 'No data returned from the query.'
    '00000': erro_generico, // "successful_completion",
    '01000': erro_generico, // "warning",
    '0100C': erro_generico, // "dynamic_result_sets_returned",
    '01008': erro_generico, // "implicit_zero_bit_padding",
    '01003': erro_generico, // "null_value_eliminated_in_set_function",
    '01007': erro_generico, // "privilege_not_granted",
    '01006': erro_generico, // "privilege_not_revoked",
    '01004': erro_generico, // "string_data_right_truncation",
    '01P01': erro_generico, // "deprecated_feature",
    '02000': nenhum_dado_encontrado, // //"no_data",
    '02001': erro_generico, // "no_additional_dynamic_result_sets_returned",
    '03000': erro_generico, // "sql_statement_not_yet_complete",
    '08000': erro_falha_conexao, // "connection_failure","connection_exception",
    '08003': erro_falha_conexao, // "connection_failure","connection_does_not_exist",
    '08006': erro_falha_conexao, // "connection_failure",
    '08001': erro_falha_conexao, // "connection_failure","sqlclient_unable_to_establish_sqlconnection",
    '08004': erro_falha_conexao, // "connection_failure","sqlserver_rejected_establishment_of_sqlconnection",
    '08007': erro_generico, // "transaction_resolution_unknown",
    '08P01': erro_generico, // "protocol_violation",
    '09000': erro_generico, // "triggered_action_exception",
    '0A000': erro_generico, // "feature_not_supported",
    '0B000': erro_generico, // "invalid_transaction_initiation",
    '0F000': erro_generico, // "locator_exception",
    '0F001': erro_generico, // "invalid_locator_specification",
    '0L000': erro_generico, // "invalid_grantor",
    '0LP01': erro_generico, // "invalid_grant_operation",
    '0P000': erro_generico, // "invalid_role_specification",
    '0Z000': erro_generico, // "diagnostics_exception",
    '0Z002': erro_generico, // "stacked_diagnostics_accessed_without_active_handler",
    20000: erro_generico, // "case_not_found",
    21000: erro_generico, // "cardinality_violation",
    22000: erro_generico, // "data_exception",
    '2202E': erro_generico, // "array_subscript_error",
    22021: erro_generico, // "character_not_in_repertoire",
    22008: erro_generico, // "datetime_field_overflow",
    22012: erro_generico, // "division_by_zero",
    22005: erro_generico, // "error_in_assignment",
    '2200B': erro_generico, // "escape_character_conflict",
    22022: erro_generico, // "indicator_overflow",
    22015: erro_generico, // "interval_field_overflow",
    '2201E': erro_generico, // "invalid_argument_for_logarithm",
    22014: erro_generico, // "invalid_argument_for_ntile_function",
    22016: erro_generico, // "invalid_argument_for_nth_value_function",
    '2201F': erro_generico, // "invalid_argument_for_power_function",
    '2201G': erro_generico, // "invalid_argument_for_width_bucket_function",
    22018: erro_generico, // "invalid_character_value_for_cast",
    22007: erro_generico, // "invalid_datetime_format",
    22019: erro_generico, // "invalid_escape_character",
    '2200D': erro_generico, // "invalid_escape_octet",
    22025: erro_generico, // "invalid_escape_sequence",
    '22P06': erro_generico, // "nonstandard_use_of_escape_character",
    22010: erro_generico, // "invalid_indicator_parameter_value",
    22023: erro_generico, // "invalid_parameter_value",
    '2201B': erro_generico, // "invalid_regular_expression",
    '2201W': erro_generico, // "invalid_row_count_in_limit_clause",
    '2201X': erro_generico, // "invalid_row_count_in_result_offset_clause",
    22009: erro_generico, // "invalid_time_zone_displacement_value",
    '2200C': erro_generico, // "invalid_use_of_escape_character",
    '2200G': erro_generico, // "most_specific_type_mismatch",
    22004: campo_nulo_nao_permitido, // "Campo nulo não permitido!",//"null_value_not_allowed",
    22002: erro_generico, // "null_value_no_indicator_parameter",
    22003: erro_generico, // "numeric_value_out_of_range",
    22026: erro_generico, // "string_data_length_mismatch",
    22001: campo_tamanho_maior_que_permitido, // "string_data_right_truncation",
    22011: erro_generico, // "substring_error",
    22027: erro_generico, // "trim_error",
    22024: erro_generico, // "unterminated_c_string",
    '2200F': erro_generico, // "zero_length_character_string",
    '22P01': erro_generico, // "floating_point_exception",
    '22P02': erro_generico, // "invalid_text_representation",
    '22P03': erro_generico, // "invalid_binary_representation",
    '22P04': erro_generico, // "bad_copy_file_format",
    '22P05': erro_generico, // "untranslatable_character",
    '2200L': erro_generico, // "not_an_xml_document",
    '2200M': erro_generico, // "invalid_xml_document",
    '2200N': erro_generico, // "invalid_xml_content",
    '2200S': erro_generico, // "invalid_xml_comment",
    '2200T': erro_generico, // "invalid_xml_processing_instruction",
    23000: erro_generico, // "integrity_constraint_violation",
    23001: erro_generico, // "restrict_violation",
    23502: campo_nulo_nao_permitido, // ",//"not_null_violation",
    23503: erro_generico, // "foreign_key_violation",
    23505: item_ja_cadastrado, // "unique_violation",
    23514: erro_generico, // "check_violation",
    '23P01': erro_ao_excluir, // "exclusion_violation",
    24000: erro_generico, // "invalid_cursor_state",
    25000: erro_generico, // "invalid_transaction_state",
    25001: erro_generico, // "active_sql_transaction",
    25002: erro_generico, // "branch_transaction_already_active",
    25008: erro_generico, // "held_cursor_requires_same_isolation_level",
    25003: erro_generico, // "inappropriate_access_mode_for_branch_transaction",
    25004: erro_generico, // "inappropriate_isolation_level_for_branch_transaction",
    25005: erro_generico, // "no_active_sql_transaction_for_branch_transaction",
    25006: erro_generico, // "read_only_sql_transaction",
    25007: erro_generico, // "schema_and_data_statement_mixing_not_supported",
    '25P01': erro_generico, // "no_active_sql_transaction",
    '25P02': erro_generico, // "in_failed_sql_transaction",
    26000: erro_generico, // "invalid_sql_statement_name",
    27000: erro_generico, // "triggered_data_change_violation",
    28000: erro_generico, // "invalid_authorization_specification",
    '28P01': erro_generico, // "invalid_password",
    '2B000': erro_generico, // "dependent_privilege_descriptors_still_exist",
    '2BP01': erro_generico, // "dependent_objects_still_exist",
    '2D000': erro_generico, // "invalid_transaction_termination",
    '2F000': erro_generico, // "sql_routine_exception",
    '2F005': erro_generico, // "function_executed_no_return_statement",
    '2F002': erro_generico, // "modifying_sql_data_not_permitted",
    '2F003': erro_generico, // "prohibited_sql_statement_attempted",
    '2F004': erro_generico, // "reading_sql_data_not_permitted",
    34000: erro_generico, // "invalid_cursor_name",
    38000: erro_generico, // "external_routine_exception",
    38001: erro_generico, // "containing_sql_not_permitted",
    38002: erro_generico, // "modifying_sql_data_not_permitted",
    38003: erro_generico, // "prohibited_sql_statement_attempted",
    38004: erro_generico, // "reading_sql_data_not_permitted",
    39000: erro_generico, // "external_routine_invocation_exception",
    39001: erro_generico, // "invalid_sqlstate_returned",
    39004: campo_nulo_nao_permitido, // null_value_not_allowed",
    '39P01': erro_generico, // "trigger_protocol_violated",
    '39P02': erro_generico, // "srf_protocol_violated",
    '3B000': erro_generico, // "savepoint_exception",
    '3B001': erro_generico, // "invalid_savepoint_specification",
    '3D000': erro_generico, // "invalid_catalog_name",
    '3F000': erro_generico, // "invalid_schema_name",
    40000: erro_generico, // "transaction_rollback",
    40002: erro_generico, // "transaction_integrity_constraint_violation",
    40001: erro_generico, // "serialization_failure",
    40003: erro_generico, // "statement_completion_unknown",
    '40P01': erro_generico, // "deadlock_detected",
    42000: erro_generico, // "syntax_error_or_access_rule_violation",
    42601: erro_generico, // "syntax_error",
    42501: erro_generico, // "insufficient_privilege",
    42846: erro_generico, // "cannot_coerce",
    42803: erro_generico, // "grouping_error",
    '42P20': erro_generico, // "windowing_error",
    '42P19': erro_generico, // "invalid_recursion",
    42830: erro_generico, // "invalid_foreign_key",
    42602: erro_generico, // "invalid_name",
    42622: erro_generico, // "name_too_long",
    42939: erro_generico, // "reserved_name",
    42804: erro_generico, // "datatype_mismatch",
    '42P18': erro_generico, // "indeterminate_datatype",
    '42P21': erro_generico, // "collation_mismatch",
    '42P22': erro_generico, // "indeterminate_collation",
    42809: erro_generico, // "wrong_object_type",
    42703: erro_generico, // "undefined_column",
    42883: erro_generico, // "undefined_function",
    '42P01': erro_generico, // "undefined_table",
    '42P02': erro_generico, // "undefined_parameter",
    42704: erro_generico, // "undefined_object",
    42701: erro_generico, // "duplicate_column",
    '42P03': erro_generico, // "duplicate_cursor",
    '42P04': erro_generico, // "duplicate_database",
    42723: erro_generico, // "duplicate_function",
    '42P05': erro_generico, // "duplicate_prepared_statement",
    '42P06': erro_generico, // "duplicate_schema",
    '42P07': erro_generico, // "duplicate_table",
    42712: erro_generico, // "duplicate_alias",
    42710: erro_generico, // "duplicate_object",
    42702: erro_generico, // "ambiguous_column",
    42725: erro_generico, // "ambiguous_function",
    '42P08': erro_generico, // "ambiguous_parameter",
    '42P09': erro_generico, // "ambiguous_alias",
    '42P10': erro_generico, // "invalid_column_reference",
    42611: erro_generico, // "invalid_column_definition",
    '42P11': erro_generico, // "invalid_cursor_definition",
    '42P12': erro_generico, // "invalid_database_definition",
    '42P13': erro_generico, // "invalid_function_definition",
    '42P14': erro_generico, // "invalid_prepared_statement_definition",
    '42P15': erro_generico, // "invalid_schema_definition",
    '42P16': erro_generico, // "invalid_table_definition",
    '42P17': erro_generico, // "invalid_object_definition",
    44000: erro_generico, // "with_check_option_violation",
    53000: erro_generico, // "insufficient_resources",
    53100: erro_generico, // ,"disk_full",
    53200: erro_generico, // "out_of_memory",
    53300: erro_generico, // "too_many_connections",
    53400: erro_generico, // "configuration_limit_exceeded",
    54000: erro_generico, // "program_limit_exceeded",
    54001: erro_generico, // "statement_too_complex",
    54011: erro_generico, // "too_many_columns",
    54023: erro_generico, // "too_many_arguments",
    55000: erro_generico, // "object_not_in_prerequisite_state",
    55006: erro_generico, // "object_in_use",
    '55P02': erro_generico, // "cant_change_runtime_param",
    '55P03': erro_generico, // "lock_not_available",
    57000: erro_generico, // "operator_intervention",
    57014: erro_generico, // "query_canceled",
    '57P01': erro_generico, // "admin_shutdown",
    '57P02': erro_generico, // "crash_shutdown",
    '57P03': erro_generico, // "cannot_connect_now",
    '57P04': erro_generico, // "database_dropped",
    58000: erro_generico, // "system_error",
    58030: erro_generico, // "io_error",
    '58P01': erro_generico, // "undefined_file",
    '58P02': erro_generico, // "duplicate_file",
    F0000: erro_generico, // "config_file_error",
    F0001: erro_generico, // "lock_file_exists",
    HV000: erro_generico, // "fdw_error",
    HV005: erro_generico, // "fdw_column_name_not_found",
    HV002: erro_generico, // "fdw_dynamic_parameter_value_needed",
    HV010: erro_generico, // "fdw_function_sequence_error",
    HV021: erro_generico, // "fdw_inconsistent_descriptor_information",
    HV024: erro_generico, // "fdw_invalid_attribute_value",
    HV007: erro_generico, // "fdw_invalid_column_name",
    HV008: erro_generico, // "fdw_invalid_column_number",
    HV004: erro_generico, // "fdw_invalid_data_type",
    HV006: erro_generico, // "fdw_invalid_data_type_descriptors",
    HV091: erro_generico, // "fdw_invalid_descriptor_field_identifier",
    HV00B: erro_generico, // "fdw_invalid_handle",
    HV00C: erro_generico, // "fdw_invalid_option_index",
    HV00D: erro_generico, // "fdw_invalid_option_name",
    HV090: erro_generico, // "fdw_invalid_string_length_or_buffer_length",
    HV00A: erro_generico, // "fdw_invalid_string_format",
    HV009: erro_generico, // "fdw_invalid_use_of_null_pointer",
    HV014: erro_generico, // "fdw_too_many_handles",
    HV001: erro_generico, // "fdw_out_of_memory",
    HV00P: erro_generico, // "fdw_no_schemas",
    HV00J: erro_generico, // "fdw_option_name_not_found",
    HV00K: erro_generico, // "fdw_reply_handle",
    HV00Q: erro_generico, // "fdw_schema_not_found",
    HV00R: erro_generico, // "fdw_table_not_found",
    HV00L: erro_generico, // "fdw_unable_to_create_execution",
    HV00M: erro_generico, // "fdw_unable_to_create_reply",
    HV00N: erro_generico, // "fdw_unable_to_establish_connection",
    P0000: erro_falha_conexao, // "plpgsql_error",
    P0001: erro_generico, // "raise_exception",
    P0002: nenhum_dado_encontrado, // "no_data_found",
    P0003: erro_generico, // "too_many_rows",
    XX000: erro_generico, // "internal_error",
    XX001: erro_generico, // "data_corrupted",
    XX002: erro_generico, // "index_corrupted"
};

const errors = (error) => {
    let userError;
    if (error.code && (error.code === 'ETIMEDOUT' || error.code === 'ENOTFOUND')) {
        userError = { message: 'Banco de dados offline! Tente novamente mais tarde.', statusCode: 400 };
    } else if (error.message === 'No data returned from the query.') {
        userError = {
            count: 0, id: 0, message: erros[error.message], data: null, statusCode: 200,
        };
    } else if (error.code && error.code === '23505') {
        userError = { message: traduzirErrorPostGre(error.constraint, `${error.code} - ${erros[error.code]}`), statusCode: 400 };
    } else if (error.code) {
        userError = { message: erros[error.code], statusCode: 400 };
    } else if (error.first.code) {
        userError = { message: traduzirErrorPostGre(error.first.constraint, `${error.first.code} - ${erros[error.first.code]}`), statusCode: 400 };
    } else {
        userError = {
            message: error.message,
            statusCode: 400,
        };
    }
    return userError;
};

module.exports =  {
    errors
};

